### ISSUE TITLE
Doesn't webpack

### ISSUE THREAD

**Issue by kejace** [rightfold/purescript-bytestrings#7]
It is unclear to me what this line should mean. When I webpack a project depending on `purescript-bytestrings`, it rightly complains about this line when it is trying to replace the `require` call with a substitute.

https://github.com/rightfold/purescript-bytestrings/blob/4671936986607bf642b380655241e8f06e4ddd8d/src/Data/ByteString.js#L3

**Comment by rightfold** [comment]
This line should be deleted, and `realGetAtOffset` should be updated to take `Just` and `Nothing` as arguments.

**Comment by rightfold** [comment]
Fixed in v5.0.2.
